import ConstructDarkModeStyle from './ConstructDarkModeStyle';
import { SetCookie, CheckCookie } from './Cookie';
import { SwitchIcon } from './Icons';

/**
 * Activates dark mode by adding the style generated by ConstructDarkModeStyle
 * function to the document tree, and setting the blinds cookie
 * 
 * @param: `NULL`
 * @returns `void`
 */
export default function ActivateDarkMode()
{
    let styles = ConstructDarkModeStyle();

    let styleTag = document.createElement("style");
    styleTag.setAttribute("id", "blinds_id");
    styleTag.textContent = styles;

    document.head.appendChild(styleTag);
    SetCookie();
    SwitchIcon();
}
