import { DeleteCookie, CheckCookie } from "./Cookie";
import { SwitchIcon } from "./Icons";

/**
 * Deactivates the dark mode if active by removing the style generated by
 * ConstructDarkModeStyle function in the document tree, and unsetting the blinds
 * cookie
 * @param: `NULL`
 * @returns `void`
 */
export default function DeactivateDarkMode()
{
    let style = "";

    if (style = document.querySelector("#blinds_id")) {
        document.head.removeChild(style);
        DeleteCookie();
        SwitchIcon();
    }
}
